### ISSUE TITLE
Improve Docs or move them to a /docs/ folder so users can edit them in push requests

### ISSUE THREAD

**Issue by MyriaCore** [gizmo385/discord.clj#7]
Basically what the title says. I'm new to clojure, so I rely on documentation to understand where bugs are coming from. In my testing of this API, I've been running into seemingly simple bugs that I don't understand the nature of, and the lack current documentation definitely doesn't help.

When I get better, maybe I could help with documentation, but because it's done via the permlocked wiki, I can't controbute through a pull request or something.

**Comment by gizmo385** [comment]
@MyriaCore I'm working on migrating the documentation over to a docs folder in the develop branch. Thanks for the suggestion :)

**Comment by gizmo385** [comment]
Addressed in #9
